"""Standard Indian government tender submission checklist templates.

Based on GFR 2017, CVC guidelines, and common e-procurement portal requirements
(GeM, CPPP, state portals). Covers Envelope A (Technical), Envelope B (Financial),
and Superscription (physical originals).

Document origin types:
- tender_provided: Format/annexure is given in the tender document — fill and submit
- self_generated: Bidder creates this document — our platform can help generate
- pre_existing: Already have it or obtain from a third party (bank, CA, govt dept)
"""

TEMPLATES = [
    # =========================================================================
    # ONLINE ONLY (Envelope A - Technical)
    # =========================================================================
    {
        "document_name": "Technical Bid Cover Letter (digitally signed)",
        "document_category": "technical",
        "submission_mode": "online",
        "is_critical": True,
        "envelope": "envelope_a",
        "cover_name": "Cover 1 - Technical Bid",
        "notarization_required": False,
        "sort_order": 1,
        "document_origin": "tender_provided",
        "format_reference": "Usually Annexure / Cover Letter format in tender",
        "obtaining_source": None,
        "can_auto_generate": True,
    },
    {
        "document_name": "Company Registration Certificate (Incorporation / MSME / LLP)",
        "document_category": "certificate",
        "submission_mode": "online",
        "is_critical": True,
        "envelope": "envelope_a",
        "cover_name": "Cover 1 - Technical Bid",
        "notarization_required": False,
        "sort_order": 2,
        "document_origin": "pre_existing",
        "format_reference": None,
        "obtaining_source": "MCA / State Registrar of Companies",
        "can_auto_generate": False,
    },
    {
        "document_name": "PAN Card Copy",
        "document_category": "certificate",
        "submission_mode": "online",
        "is_critical": True,
        "envelope": "envelope_a",
        "cover_name": "Cover 1 - Technical Bid",
        "notarization_required": False,
        "sort_order": 3,
        "document_origin": "pre_existing",
        "format_reference": None,
        "obtaining_source": "Income Tax Department",
        "can_auto_generate": False,
    },
    {
        "document_name": "GST Registration Certificate",
        "document_category": "certificate",
        "submission_mode": "online",
        "is_critical": True,
        "envelope": "envelope_a",
        "cover_name": "Cover 1 - Technical Bid",
        "notarization_required": False,
        "sort_order": 4,
        "document_origin": "pre_existing",
        "format_reference": None,
        "obtaining_source": "GST Portal (gst.gov.in)",
        "can_auto_generate": False,
    },
    {
        "document_name": "Non-Blacklisting Self Declaration",
        "document_category": "declaration",
        "submission_mode": "online",
        "is_critical": True,
        "envelope": "envelope_a",
        "cover_name": "Cover 1 - Technical Bid",
        "notarization_required": False,
        "sort_order": 5,
        "document_origin": "tender_provided",
        "format_reference": "Standard Annexure in tender (check Section / Annexures)",
        "obtaining_source": None,
        "can_auto_generate": True,
    },
    {
        "document_name": "No Deviation / No Assumption Statement",
        "document_category": "declaration",
        "submission_mode": "online",
        "is_critical": True,
        "envelope": "envelope_a",
        "cover_name": "Cover 1 - Technical Bid",
        "notarization_required": False,
        "sort_order": 6,
        "document_origin": "tender_provided",
        "format_reference": "Standard Annexure in tender",
        "obtaining_source": None,
        "can_auto_generate": True,
    },
    {
        "document_name": "Acceptance of Terms & Conditions",
        "document_category": "declaration",
        "submission_mode": "online",
        "is_critical": True,
        "envelope": "envelope_a",
        "cover_name": "Cover 1 - Technical Bid",
        "notarization_required": False,
        "sort_order": 7,
        "document_origin": "tender_provided",
        "format_reference": "Standard Annexure in tender",
        "obtaining_source": None,
        "can_auto_generate": True,
    },
    {
        "document_name": "Make in India / Local Content Declaration",
        "document_category": "declaration",
        "submission_mode": "online",
        "is_critical": True,
        "envelope": "envelope_a",
        "cover_name": "Cover 1 - Technical Bid",
        "notarization_required": False,
        "sort_order": 8,
        "document_origin": "tender_provided",
        "format_reference": "Standard MII format (PP-PPO 2017 / DPIIT Order)",
        "obtaining_source": None,
        "can_auto_generate": True,
    },
    {
        "document_name": "Land Border Country Declaration (China clause)",
        "document_category": "declaration",
        "submission_mode": "online",
        "is_critical": True,
        "envelope": "envelope_a",
        "cover_name": "Cover 1 - Technical Bid",
        "notarization_required": False,
        "sort_order": 9,
        "document_origin": "tender_provided",
        "format_reference": "DoE Order No. 6/18/2019-PPD dated 23.07.2020 format",
        "obtaining_source": None,
        "can_auto_generate": True,
    },
    {
        "document_name": "Integrity Pact (signed and witnessed)",
        "document_category": "legal",
        "submission_mode": "online",
        "is_critical": False,
        "envelope": "envelope_a",
        "cover_name": "Cover 1 - Technical Bid",
        "notarization_required": False,
        "sort_order": 10,
        "document_origin": "tender_provided",
        "format_reference": "CVC format provided in tender",
        "obtaining_source": None,
        "can_auto_generate": False,
    },
    {
        "document_name": "Company Profile / Capability Statement",
        "document_category": "company_profile",
        "submission_mode": "online",
        "is_critical": False,
        "envelope": "envelope_a",
        "cover_name": "Cover 1 - Technical Bid",
        "notarization_required": False,
        "sort_order": 11,
        "document_origin": "self_generated",
        "format_reference": None,
        "obtaining_source": None,
        "can_auto_generate": True,
    },
    {
        "document_name": "Past Work Order Copies (scanned)",
        "document_category": "experience",
        "submission_mode": "online",
        "is_critical": False,
        "envelope": "envelope_a",
        "cover_name": "Cover 1 - Technical Bid",
        "notarization_required": False,
        "sort_order": 12,
        "document_origin": "pre_existing",
        "format_reference": None,
        "obtaining_source": "Past Clients / Procuring Entities",
        "can_auto_generate": False,
    },
    {
        "document_name": "Technical Compliance Matrix",
        "document_category": "technical",
        "submission_mode": "online",
        "is_critical": True,
        "envelope": "envelope_a",
        "cover_name": "Cover 1 - Technical Bid",
        "notarization_required": False,
        "sort_order": 13,
        "document_origin": "tender_provided",
        "format_reference": "BoQ / Technical Specifications format in tender",
        "obtaining_source": None,
        "can_auto_generate": False,
    },
    {
        "document_name": "Product Datasheets / Catalogues",
        "document_category": "technical",
        "submission_mode": "online",
        "is_critical": False,
        "envelope": "envelope_a",
        "cover_name": "Cover 1 - Technical Bid",
        "notarization_required": False,
        "sort_order": 14,
        "document_origin": "pre_existing",
        "format_reference": None,
        "obtaining_source": "OEM / Product Manufacturer",
        "can_auto_generate": False,
    },
    {
        "document_name": "MSME / Udyam Registration Certificate",
        "document_category": "certificate",
        "submission_mode": "online",
        "is_critical": False,
        "envelope": "envelope_a",
        "cover_name": "Cover 1 - Technical Bid",
        "notarization_required": False,
        "sort_order": 15,
        "document_origin": "pre_existing",
        "format_reference": None,
        "obtaining_source": "Udyam Portal (udyamregistration.gov.in)",
        "can_auto_generate": False,
    },

    # =========================================================================
    # ONLINE ONLY (Envelope B - Financial)
    # =========================================================================
    {
        "document_name": "Financial Bid / BoQ (digitally signed)",
        "document_category": "financial",
        "submission_mode": "online",
        "is_critical": True,
        "envelope": "envelope_b",
        "cover_name": "Cover 2 - Financial Bid",
        "notarization_required": False,
        "sort_order": 16,
        "document_origin": "tender_provided",
        "format_reference": "BoQ / Price Schedule format in tender",
        "obtaining_source": None,
        "can_auto_generate": False,
    },
    {
        "document_name": "Price Schedule / Rate Card",
        "document_category": "financial",
        "submission_mode": "online",
        "is_critical": False,
        "envelope": "envelope_b",
        "cover_name": "Cover 2 - Financial Bid",
        "notarization_required": False,
        "sort_order": 17,
        "document_origin": "tender_provided",
        "format_reference": "Price schedule format in tender",
        "obtaining_source": None,
        "can_auto_generate": False,
    },

    # =========================================================================
    # OFFLINE ONLY
    # =========================================================================
    {
        "document_name": "Original EMD Instrument (DD/BG)",
        "document_category": "emd",
        "submission_mode": "offline",
        "is_critical": False,
        "envelope": "superscription",
        "cover_name": "Superscription Envelope",
        "notarization_required": False,
        "sort_order": 18,
        "document_origin": "pre_existing",
        "format_reference": None,
        "obtaining_source": "Bank (Demand Draft / Bank Guarantee)",
        "can_auto_generate": False,
    },
    {
        "document_name": "Tender Fee (Original DD)",
        "document_category": "emd",
        "submission_mode": "offline",
        "is_critical": False,
        "envelope": "superscription",
        "cover_name": "Superscription Envelope",
        "notarization_required": False,
        "sort_order": 19,
        "document_origin": "pre_existing",
        "format_reference": None,
        "obtaining_source": "Bank (Demand Draft)",
        "can_auto_generate": False,
    },
    {
        "document_name": "Original Power of Attorney / Board Resolution",
        "document_category": "legal",
        "submission_mode": "offline",
        "is_critical": False,
        "envelope": "superscription",
        "cover_name": "Superscription Envelope",
        "notarization_required": True,
        "notarization_type": "non_judicial",
        "sort_order": 20,
        "document_origin": "self_generated",
        "format_reference": None,
        "obtaining_source": None,
        "can_auto_generate": True,
    },
    {
        "document_name": "Notarized Affidavits (Non-Blacklisting, No-Relation, etc.)",
        "document_category": "declaration",
        "submission_mode": "offline",
        "is_critical": False,
        "envelope": "envelope_a",
        "cover_name": "Cover 1 - Technical Bid",
        "notarization_required": True,
        "notarization_type": "judicial",
        "sort_order": 21,
        "document_origin": "tender_provided",
        "format_reference": "Affidavit format as per tender Annexure (on stamp paper)",
        "obtaining_source": None,
        "can_auto_generate": True,
    },
    {
        "document_name": "Original Partnership Deed / MOA & AOA",
        "document_category": "legal",
        "submission_mode": "offline",
        "is_critical": False,
        "envelope": "envelope_a",
        "cover_name": "Cover 1 - Technical Bid",
        "notarization_required": True,
        "notarization_type": "non_judicial",
        "sort_order": 22,
        "document_origin": "pre_existing",
        "format_reference": None,
        "obtaining_source": "Company Legal Records / ROC",
        "can_auto_generate": False,
    },
    {
        "document_name": "Sealed Price Bid (if physical envelope required)",
        "document_category": "financial",
        "submission_mode": "offline",
        "is_critical": False,
        "envelope": "envelope_b",
        "cover_name": "Cover 2 - Financial Bid",
        "notarization_required": False,
        "sort_order": 23,
        "document_origin": "tender_provided",
        "format_reference": "Price bid format from tender",
        "obtaining_source": None,
        "can_auto_generate": False,
    },

    # =========================================================================
    # BOTH (online + offline)
    # =========================================================================
    {
        "document_name": "EMD / Bid Security Declaration (BSD)",
        "document_category": "emd",
        "submission_mode": "both",
        "is_critical": False,
        "envelope": "envelope_a",
        "cover_name": "Cover 1 - Technical Bid",
        "notarization_required": True,
        "notarization_type": "non_judicial",
        "sort_order": 24,
        "document_origin": "tender_provided",
        "format_reference": "GFR 170 / Standard BSD format in tender",
        "obtaining_source": None,
        "can_auto_generate": True,
    },
    {
        "document_name": "Tender Fee Receipt",
        "document_category": "emd",
        "submission_mode": "both",
        "is_critical": False,
        "envelope": "envelope_a",
        "cover_name": "Cover 1 - Technical Bid",
        "notarization_required": False,
        "sort_order": 25,
        "document_origin": "pre_existing",
        "format_reference": None,
        "obtaining_source": "E-Procurement Portal / Bank",
        "can_auto_generate": False,
    },
    {
        "document_name": "OEM Authorization / MAF Letters",
        "document_category": "oem",
        "submission_mode": "both",
        "is_critical": False,
        "envelope": "envelope_a",
        "cover_name": "Cover 1 - Technical Bid",
        "notarization_required": False,
        "sort_order": 26,
        "document_origin": "pre_existing",
        "format_reference": None,
        "obtaining_source": "OEM / Principal Manufacturer",
        "can_auto_generate": False,
    },
    {
        "document_name": "Solvency Certificate from Bank",
        "document_category": "financial",
        "submission_mode": "both",
        "is_critical": False,
        "envelope": "envelope_a",
        "cover_name": "Cover 1 - Technical Bid",
        "notarization_required": False,
        "sort_order": 27,
        "document_origin": "pre_existing",
        "format_reference": None,
        "obtaining_source": "Bank (on bank letterhead)",
        "can_auto_generate": False,
    },
    {
        "document_name": "Audited Balance Sheet & P&L (last 3 years)",
        "document_category": "financial",
        "submission_mode": "both",
        "is_critical": True,
        "envelope": "envelope_a",
        "cover_name": "Cover 1 - Technical Bid",
        "notarization_required": False,
        "sort_order": 28,
        "document_origin": "pre_existing",
        "format_reference": None,
        "obtaining_source": "Chartered Accountant / Statutory Auditor",
        "can_auto_generate": False,
    },
    {
        "document_name": "CA Certificate for Annual Turnover",
        "document_category": "financial",
        "submission_mode": "both",
        "is_critical": True,
        "envelope": "envelope_a",
        "cover_name": "Cover 1 - Technical Bid",
        "notarization_required": False,
        "sort_order": 29,
        "document_origin": "pre_existing",
        "format_reference": None,
        "obtaining_source": "Chartered Accountant (on CA letterhead with UDIN)",
        "can_auto_generate": False,
    },
    {
        "document_name": "Experience / Completion Certificates",
        "document_category": "experience",
        "submission_mode": "both",
        "is_critical": True,
        "envelope": "envelope_a",
        "cover_name": "Cover 1 - Technical Bid",
        "notarization_required": False,
        "sort_order": 30,
        "document_origin": "pre_existing",
        "format_reference": None,
        "obtaining_source": "Past Clients / Procuring Entities",
        "can_auto_generate": False,
    },
    {
        "document_name": "Authorization Letter for Bid Signing",
        "document_category": "legal",
        "submission_mode": "both",
        "is_critical": True,
        "envelope": "envelope_a",
        "cover_name": "Cover 1 - Technical Bid",
        "notarization_required": True,
        "notarization_type": "non_judicial",
        "sort_order": 31,
        "document_origin": "self_generated",
        "format_reference": None,
        "obtaining_source": None,
        "can_auto_generate": True,
    },

    # =========================================================================
    # MSME EXEMPTION DECLARATIONS (GFR 2017, PP-PPO 2012, MSMED Act)
    # =========================================================================
    {
        "document_name": "EMD Exemption Declaration (MSME under GFR 170(i))",
        "document_category": "declaration",
        "submission_mode": "online",
        "is_critical": False,
        "envelope": "envelope_a",
        "cover_name": "Cover 1 - Technical Bid",
        "notarization_required": False,
        "sort_order": 32,
        "document_origin": "self_generated",
        "format_reference": None,
        "obtaining_source": None,
        "can_auto_generate": True,
    },
    {
        "document_name": "Turnover Exemption Declaration (MSME under PP-PPO 2012)",
        "document_category": "declaration",
        "submission_mode": "online",
        "is_critical": False,
        "envelope": "envelope_a",
        "cover_name": "Cover 1 - Technical Bid",
        "notarization_required": False,
        "sort_order": 33,
        "document_origin": "self_generated",
        "format_reference": None,
        "obtaining_source": None,
        "can_auto_generate": True,
    },
    {
        "document_name": "Prior Experience Exemption Declaration (MSME under GFR 170)",
        "document_category": "declaration",
        "submission_mode": "online",
        "is_critical": False,
        "envelope": "envelope_a",
        "cover_name": "Cover 1 - Technical Bid",
        "notarization_required": False,
        "sort_order": 34,
        "document_origin": "self_generated",
        "format_reference": None,
        "obtaining_source": None,
        "can_auto_generate": True,
    },
    {
        "document_name": "Tender Fee Exemption Request (MSME)",
        "document_category": "declaration",
        "submission_mode": "online",
        "is_critical": False,
        "envelope": "envelope_a",
        "cover_name": "Cover 1 - Technical Bid",
        "notarization_required": False,
        "sort_order": 35,
        "document_origin": "self_generated",
        "format_reference": None,
        "obtaining_source": None,
        "can_auto_generate": True,
    },
    {
        "document_name": "DPIIT Startup Recognition Certificate (if applicable)",
        "document_category": "certificate",
        "submission_mode": "online",
        "is_critical": False,
        "envelope": "envelope_a",
        "cover_name": "Cover 1 - Technical Bid",
        "notarization_required": False,
        "sort_order": 36,
        "document_origin": "pre_existing",
        "format_reference": None,
        "obtaining_source": "DPIIT Portal (dpiit.gov.in)",
        "can_auto_generate": False,
    },
    {
        "document_name": "Class I / Class II Local Supplier Certificate (PP-PPO)",
        "document_category": "declaration",
        "submission_mode": "online",
        "is_critical": False,
        "envelope": "envelope_a",
        "cover_name": "Cover 1 - Technical Bid",
        "notarization_required": False,
        "sort_order": 37,
        "document_origin": "tender_provided",
        "format_reference": "Standard PP-PPO / Make in India format in tender",
        "obtaining_source": None,
        "can_auto_generate": True,
    },

    # =========================================================================
    # IT / TECHNICAL DECLARATIONS
    # =========================================================================
    {
        "document_name": "Malicious Code Free Certificate / Declaration",
        "document_category": "declaration",
        "submission_mode": "online",
        "is_critical": False,
        "envelope": "envelope_a",
        "cover_name": "Cover 1 - Technical Bid",
        "notarization_required": False,
        "sort_order": 38,
        "document_origin": "tender_provided",
        "format_reference": "Usually standard Annexure in IT tenders",
        "obtaining_source": None,
        "can_auto_generate": True,
    },
    {
        "document_name": "Warranty Declaration / Warranty Terms Letter",
        "document_category": "declaration",
        "submission_mode": "online",
        "is_critical": False,
        "envelope": "envelope_a",
        "cover_name": "Cover 1 - Technical Bid",
        "notarization_required": False,
        "sort_order": 39,
        "document_origin": "self_generated",
        "format_reference": None,
        "obtaining_source": None,
        "can_auto_generate": True,
    },
    {
        "document_name": "Hardware / Software Warranty Terms (3-5 year)",
        "document_category": "technical",
        "submission_mode": "online",
        "is_critical": False,
        "envelope": "envelope_a",
        "cover_name": "Cover 1 - Technical Bid",
        "notarization_required": False,
        "sort_order": 40,
        "document_origin": "self_generated",
        "format_reference": None,
        "obtaining_source": None,
        "can_auto_generate": True,
    },
    {
        "document_name": "Escalation Matrix (Support Contacts & SLA)",
        "document_category": "technical",
        "submission_mode": "online",
        "is_critical": False,
        "envelope": "envelope_a",
        "cover_name": "Cover 1 - Technical Bid",
        "notarization_required": False,
        "sort_order": 41,
        "document_origin": "self_generated",
        "format_reference": None,
        "obtaining_source": None,
        "can_auto_generate": True,
    },
    {
        "document_name": "Bidder as OEM Declaration (Self-Manufacturing)",
        "document_category": "declaration",
        "submission_mode": "online",
        "is_critical": False,
        "envelope": "envelope_a",
        "cover_name": "Cover 1 - Technical Bid",
        "notarization_required": False,
        "sort_order": 42,
        "document_origin": "self_generated",
        "format_reference": None,
        "obtaining_source": None,
        "can_auto_generate": True,
    },
    {
        "document_name": "Cyber Security / Anti-Virus Compliance Declaration",
        "document_category": "declaration",
        "submission_mode": "online",
        "is_critical": False,
        "envelope": "envelope_a",
        "cover_name": "Cover 1 - Technical Bid",
        "notarization_required": False,
        "sort_order": 43,
        "document_origin": "self_generated",
        "format_reference": None,
        "obtaining_source": None,
        "can_auto_generate": True,
    },
    {
        "document_name": "SLA Commitment / Service Level Agreement Letter",
        "document_category": "technical",
        "submission_mode": "online",
        "is_critical": False,
        "envelope": "envelope_a",
        "cover_name": "Cover 1 - Technical Bid",
        "notarization_required": False,
        "sort_order": 44,
        "document_origin": "self_generated",
        "format_reference": None,
        "obtaining_source": None,
        "can_auto_generate": True,
    },
    {
        "document_name": "Manpower Deployment Plan / Resource Matrix",
        "document_category": "technical",
        "submission_mode": "online",
        "is_critical": False,
        "envelope": "envelope_a",
        "cover_name": "Cover 1 - Technical Bid",
        "notarization_required": False,
        "sort_order": 45,
        "document_origin": "self_generated",
        "format_reference": None,
        "obtaining_source": None,
        "can_auto_generate": True,
    },
    {
        "document_name": "Project Implementation Methodology / Approach",
        "document_category": "technical",
        "submission_mode": "online",
        "is_critical": False,
        "envelope": "envelope_a",
        "cover_name": "Cover 1 - Technical Bid",
        "notarization_required": False,
        "sort_order": 46,
        "document_origin": "self_generated",
        "format_reference": None,
        "obtaining_source": None,
        "can_auto_generate": True,
    },

    # =========================================================================
    # FINANCIAL / COMPLIANCE DECLARATIONS
    # =========================================================================
    {
        "document_name": "Financial Standing / Net Worth Declaration",
        "document_category": "declaration",
        "submission_mode": "online",
        "is_critical": False,
        "envelope": "envelope_a",
        "cover_name": "Cover 1 - Technical Bid",
        "notarization_required": False,
        "sort_order": 47,
        "document_origin": "tender_provided",
        "format_reference": "Standard Annexure in tender",
        "obtaining_source": None,
        "can_auto_generate": True,
    },
    {
        "document_name": "No Conflict of Interest Declaration",
        "document_category": "declaration",
        "submission_mode": "online",
        "is_critical": False,
        "envelope": "envelope_a",
        "cover_name": "Cover 1 - Technical Bid",
        "notarization_required": False,
        "sort_order": 48,
        "document_origin": "tender_provided",
        "format_reference": "Standard Annexure in tender",
        "obtaining_source": None,
        "can_auto_generate": True,
    },
    {
        "document_name": "No Relation with Procuring Entity Declaration",
        "document_category": "declaration",
        "submission_mode": "online",
        "is_critical": False,
        "envelope": "envelope_a",
        "cover_name": "Cover 1 - Technical Bid",
        "notarization_required": True,
        "notarization_type": "judicial",
        "sort_order": 49,
        "document_origin": "tender_provided",
        "format_reference": "Affidavit format in tender (on judicial stamp paper)",
        "obtaining_source": None,
        "can_auto_generate": True,
    },
    {
        "document_name": "Litigation / Arbitration Declaration",
        "document_category": "declaration",
        "submission_mode": "online",
        "is_critical": False,
        "envelope": "envelope_a",
        "cover_name": "Cover 1 - Technical Bid",
        "notarization_required": False,
        "sort_order": 50,
        "document_origin": "tender_provided",
        "format_reference": "Standard Annexure in tender",
        "obtaining_source": None,
        "can_auto_generate": True,
    },
    {
        "document_name": "Clean Track Record / No Criminal Case Declaration",
        "document_category": "declaration",
        "submission_mode": "online",
        "is_critical": False,
        "envelope": "envelope_a",
        "cover_name": "Cover 1 - Technical Bid",
        "notarization_required": True,
        "notarization_type": "judicial",
        "sort_order": 51,
        "document_origin": "tender_provided",
        "format_reference": "Affidavit format in tender (on judicial stamp paper)",
        "obtaining_source": None,
        "can_auto_generate": True,
    },
    {
        "document_name": "Confidentiality / NDA Undertaking",
        "document_category": "legal",
        "submission_mode": "online",
        "is_critical": False,
        "envelope": "envelope_a",
        "cover_name": "Cover 1 - Technical Bid",
        "notarization_required": False,
        "sort_order": 52,
        "document_origin": "tender_provided",
        "format_reference": "NDA format in tender (if provided)",
        "obtaining_source": None,
        "can_auto_generate": True,
    },
    {
        "document_name": "GeM GTC Compliance Declaration (if GeM portal)",
        "document_category": "declaration",
        "submission_mode": "online",
        "is_critical": False,
        "envelope": "envelope_a",
        "cover_name": "Cover 1 - Technical Bid",
        "notarization_required": False,
        "sort_order": 53,
        "document_origin": "tender_provided",
        "format_reference": "GeM General Terms & Conditions format",
        "obtaining_source": None,
        "can_auto_generate": False,
    },

    # =========================================================================
    # REGISTRATION / COMPLIANCE CERTIFICATES
    # =========================================================================
    {
        "document_name": "EPF Registration Certificate",
        "document_category": "certificate",
        "submission_mode": "online",
        "is_critical": False,
        "envelope": "envelope_a",
        "cover_name": "Cover 1 - Technical Bid",
        "notarization_required": False,
        "sort_order": 54,
        "document_origin": "pre_existing",
        "format_reference": None,
        "obtaining_source": "EPFO Portal (epfindia.gov.in)",
        "can_auto_generate": False,
    },
    {
        "document_name": "ESI Registration Certificate",
        "document_category": "certificate",
        "submission_mode": "online",
        "is_critical": False,
        "envelope": "envelope_a",
        "cover_name": "Cover 1 - Technical Bid",
        "notarization_required": False,
        "sort_order": 55,
        "document_origin": "pre_existing",
        "format_reference": None,
        "obtaining_source": "ESIC Portal (esic.gov.in)",
        "can_auto_generate": False,
    },
    {
        "document_name": "ISO Certifications (9001 / 27001 / 20000 as applicable)",
        "document_category": "certificate",
        "submission_mode": "online",
        "is_critical": False,
        "envelope": "envelope_a",
        "cover_name": "Cover 1 - Technical Bid",
        "notarization_required": False,
        "sort_order": 56,
        "document_origin": "pre_existing",
        "format_reference": None,
        "obtaining_source": "ISO Certification Body (BSI, TUV, Bureau Veritas, etc.)",
        "can_auto_generate": False,
    },
]


def get_all_templates() -> list[dict]:
    """Return all standard checklist templates."""
    return TEMPLATES


def get_templates_by_mode(mode: str) -> list[dict]:
    """Return templates filtered by submission mode."""
    if mode == "both":
        return [t for t in TEMPLATES if t["submission_mode"] == "both"]
    return [t for t in TEMPLATES if t["submission_mode"] in (mode, "both")]


def get_templates_by_category(category: str) -> list[dict]:
    """Return templates filtered by document category."""
    return [t for t in TEMPLATES if t["document_category"] == category]


def get_templates_by_envelope(envelope: str) -> list[dict]:
    """Return templates filtered by envelope."""
    return [t for t in TEMPLATES if t["envelope"] == envelope]


def get_templates_by_origin(origin: str) -> list[dict]:
    """Return templates filtered by document origin."""
    return [t for t in TEMPLATES if t["document_origin"] == origin]


def get_cover_summary() -> list[dict]:
    """Return a summary of covers/envelopes with their document counts."""
    covers = {}
    for t in TEMPLATES:
        cover = t.get("cover_name") or t.get("envelope") or "Unassigned"
        envelope = t.get("envelope", "")
        if cover not in covers:
            covers[cover] = {"cover_name": cover, "envelope": envelope, "documents": [], "critical_count": 0}
        covers[cover]["documents"].append(t["document_name"])
        if t["is_critical"]:
            covers[cover]["critical_count"] += 1
    return list(covers.values())
