namespace ComplaintManagement.Domain.Enums;

/// <summary>
/// Represents actions that can be performed on user passwords
/// Used for audit logging and tracking password lifecycle events
/// </summary>
public enum PasswordAction
{
    /// <summary>
    /// Password was set by an administrator
    /// </summary>
    SetByAdmin = 1,

    /// <summary>
    /// Password was changed by the user themselves
    /// </summary>
    ChangedByUser = 2,

    /// <summary>
    /// Password was reset by an administrator
    /// </summary>
    ResetByAdmin = 3,

    /// <summary>
    /// Password was auto-generated by the system
    /// </summary>
    AutoGenerated = 4,

    /// <summary>
    /// Failed password change attempt
    /// </summary>
    ChangeFailed = 5,

    /// <summary>
    /// Password expired and requires change
    /// </summary>
    Expired = 6,

    /// <summary>
    /// Password was sent via email
    /// </summary>
    SentViaEmail = 7,

    /// <summary>
    /// Account was locked due to too many failed attempts
    /// </summary>
    AccountLocked = 8,

    /// <summary>
    /// Account was unlocked by administrator
    /// </summary>
    AccountUnlocked = 9,

    /// <summary>
    /// Password verification succeeded
    /// </summary>
    VerificationSuccess = 10,

    /// <summary>
    /// Password verification failed
    /// </summary>
    VerificationFailed = 11,

    /// <summary>
    /// Password reset was requested (self-service)
    /// </summary>
    PasswordResetRequested = 12,

    /// <summary>
    /// Password reset was completed (self-service)
    /// </summary>
    PasswordResetCompleted = 13
}
